services:
  api-gateway:
    restart: always
    build:
      context: ./backend/api-gateway
    ports:
      - 3010:3010
    volumes:
      - ./backend/api-gateway:/api-gateway
      - ./backend/api-gateway/node_modules:/api-gateway/node_modules
  auth-service:
    restart: always
    build:
      context: ./backend/services/auth-service
    depends_on:
      - broker
    volumes:
      - ./backend/services/auth-service:/auth-service
      - ./backend/services/auth-service/node_modules:/auth-service/node_modules
  user-service:
    restart: always
    build:
      context: ./backend/services/user-service
    depends_on:
      - broker
    volumes:
      - ./backend/services/user-service:/user-service
  zookeeper:
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  broker:
    image: wurstmeister/kafka:2.11-1.1.1
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_HOST_NAME: "broker"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: "PLAINTEXT://:29092,PLAINTEXT_HOST://:9092"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "test-topic:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.1
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'